# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Hyu_gabaru Ryu_ichi <hyu_gabaru@yahoo.co.jp>, 2009.
#
msgid ""
msgstr ""
"Project-Id-Version: python-meh 1\n"
"Report-Msgid-Bugs-To: fedora-trans-ja@redhat.com\n"
"POT-Creation-Date: 2009-07-16 15:00-0400\n"
"PO-Revision-Date: 2009-08-29 20:01+0900\n"
"Last-Translator: Hyu_gabaru Ryu_ichi <hyu_gabaru@yahoo.co.jp>\n"
"Language-Team: Japanese <fedora-trans-ja@redhat.com>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../src/handler.py:209
msgid "Dump Written"
msgstr "ダンプが書かれました"

#: ../src/handler.py:210
msgid ""
"The error file has been successfully written to the disk.  The program will "
"now exit."
msgstr "エラーファイルは正常にディスクに書かれました。プログラムは終了します。"

#: ../src/handler.py:215
msgid "Dump Not Written"
msgstr "ダンプが書かれませんでした"

#: ../src/handler.py:216
msgid "There was a problem writing the error report."
msgstr "エラーレポートの書き込みに問題がありました。"

#: ../src/handler.py:219
msgid "No Network Available"
msgstr "ネットワークが利用不可能"

#: ../src/handler.py:220
msgid ""
"Cannot save a bug report since there is no active network device available."
msgstr ""
"アクティブなネットワーク装置が利用不可能なのでバグレポートを保存できません。"

#: ../src/savers.py:34
#, python-format
msgid ""
"Your bug could not be filed due to the following error when communicating "
"with bugzilla:\n"
"\n"
"%s"
msgstr ""
"あなたのバグは bugzilla との通信時に以下のエラーのため、記録できません"
"でした。\n"
"\n"
"%s"

#: ../src/savers.py:37
#, python-format
msgid ""
"Your bug could not be filed due to bad information in the bug fields.  This "
"is most likely an error in the bug filing program:\n"
"\n"
"%s"
msgstr ""
"あなたのバグはバグ領域にある悪い情報のため、記録できませんでした。これは"
"たいていはバグ記録プログラムのエラーです:\n"
"\n"
"%s"

#: ../src/savers.py:41
msgid "Unable To File Bug"
msgstr "バグ記録不可"

#: ../src/savers.py:47
msgid "Bug Filing Not Supported"
msgstr "バグ記録はサポートされていません"

#: ../src/savers.py:48
msgid ""
"Your distribution does not provide a supported bug filing system, so you "
"cannot save your exception this way."
msgstr ""
"あなたのディストリビューションはサポートしているバグ記録システムを提供して"
"いないので、あなたの例外はこの方法では保存できません。"

#: ../src/savers.py:54
msgid "Invalid Bug Information"
msgstr "不正なバグ情報"

#: ../src/savers.py:55
msgid "Please provide a valid username, password, and short bug description."
msgstr "正しい利用者名と、パスワード、簡単なバグ記述を入れてください。"

#: ../src/savers.py:62
msgid "Unable To Login"
msgstr "ログインできません"

#: ../src/savers.py:63
#, python-format
msgid ""
"There was an error logging into %s using the provided username and password."
msgstr ""
"指定された利用者名とパスワードで %s にログインする時にエラーになりました。"

#. Tell the user we created a new bug for them and that they should
#. go add a descriptive comment.
#: ../src/savers.py:99
msgid "Bug Created"
msgstr "バグが作成されました"

#: ../src/savers.py:100
#, python-format
msgid ""
"A new bug has been created with your traceback attached. Please add "
"additional information such as what you were doing when you encountered the "
"bug, screenshots, and whatever else is appropriate to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"添付のあなたのトレースバックと共に新しいバグが作成されました。以下のバグに"
"バグに出会った時に何をしていたかや、スクリーンショットなど何でもいいから"
"追加情報を付加してください:\n"
"\n"
"%s/%s"

#. Tell the user which bug they've been CC'd on and that they should
#. go add a descriptive comment.
#: ../src/savers.py:114
msgid "Bug Updated"
msgstr "バグが更新されました"

#: ../src/savers.py:115
#, python-format
msgid ""
"A bug with your information already exists.  Your account has been added to "
"the CC list and your traceback added as a comment.  Please add additional "
"descriptive information to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"あなたの情報のバグは既にあります。あなたのアカウントは CC リストに追加され、"
"あなたのトレースバックはコメントとして追加されます。以下のバグに追加の記述"
"情報を追加してください:\n"
"\n"
"%s/%s"

#. Set the buttons.
#: ../src/ui/gui.py:85
msgid "_Debug"
msgstr "デバッグ(_D)"

#: ../src/ui/gui.py:87 ../src/ui/gui.py:152
msgid "_Exit"
msgstr "終了(_E)"

#: ../src/ui/gui.py:92
msgid ""
"An unhandled exception has occurred.  This is most likely a bug.  Please "
"save a copy of the detailed exception and file a bug report."
msgstr ""
"取り扱えない例外が発生しました。これはたいていはバグです。詳細な例外の"
"コピーを保存し、バグレポートを作成してください。"

#: tmp/detailed-dialog.glade.h:1
msgid "Info"
msgstr "情報"

#: tmp/detailed-dialog.glade.h:2
msgid "_Details"
msgstr "詳細(_D)"

#: tmp/exnSave.glade.h:1
msgid "Bug _description"
msgstr "バグ記述(_D)"

#: tmp/exnSave.glade.h:2
msgid "Destination _file"
msgstr "ファイルの宛先(_F)"

#: tmp/exnSave.glade.h:3
msgid ""
"Local storage\n"
"Bugzilla\n"
"Remote server (scp)"
msgstr ""
"ローカル記憶\n"
"バグジラ\n"
"リモートサーバー (scp)"

#: tmp/exnSave.glade.h:6
msgid "Please choose a destination for saving your traceback."
msgstr "あなたのトレースバックを保存する宛先を選んでください。"

#: tmp/exnSave.glade.h:7
msgid "Save"
msgstr "保存"

#: tmp/exnSave.glade.h:8
msgid "Select A File"
msgstr "ファイルの選択"

#: tmp/exnSave.glade.h:9
msgid "_Host (host:port)"
msgstr "ホスト (ホスト:ポート)(_H)"

#: tmp/exnSave.glade.h:10
msgid "_Password"
msgstr "パスワード"

#: tmp/exnSave.glade.h:11
msgid "_User name"
msgstr "利用者名"
