# translation of python-meh.master.python-meh.po to Kannada
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Shankar Prasad <svenkate@redhat.com>, 2009.
msgid ""
msgstr ""
"Project-Id-Version: python-meh.master.python-meh\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-07-16 15:00-0400\n"
"PO-Revision-Date: 2009-09-10 00:09+0530\n"
"Last-Translator: Shankar Prasad <svenkate@redhat.com>\n"
"Language-Team: Kannada <en@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: KBabel 1.11.4\n"
"Plural-Forms:  nplurals=2; plural=(n != 1);\n"

#: ../src/handler.py:209
msgid "Dump Written"
msgstr "ಕುಸಿತವನ್ನು ಬರೆಯಲಾಗಿದೆ"

#: ../src/handler.py:210
msgid ""
"The error file has been successfully written to the disk.  The program will "
"now exit."
msgstr "ದೋಷ ಕಡತವನ್ನು ಡಿಸ್ಕಿಗೆ ಯಶಸ್ವಿಯಾಗಿ ಬರೆಯಲಾಗಿದೆ. ಪ್ರೊಗ್ರಾಮ್ ಈಗ ನಿರ್ಗಮಿಸುತ್ತದೆ."

#: ../src/handler.py:215
msgid "Dump Not Written"
msgstr "ಕುಸಿತವನ್ನು ಬರೆಯಲಾಗಿಲ್ಲ"

#: ../src/handler.py:216
msgid "There was a problem writing the error report."
msgstr "ದೋಷ ವರದಿಯನ್ನು ಬರೆಯುವಲ್ಲಿ ಒಂದು ತೊಂದರೆ ಉಂಟಾಗಿದೆ."

#: ../src/handler.py:219
msgid "No Network Available"
msgstr "ಯಾವುದೆ ಜಾಲಬಂಧವು ಲಭ್ಯವಿಲ್ಲ"

#: ../src/handler.py:220
msgid "Cannot save a bug report since there is no active network device available."
msgstr "ಯಾವುದೆ ಸಕ್ರಿಯ ಜಾಲ ಸಾಧನವು ಲಭ್ಯವಿರದ ಕಾರಣ ದೋಷ ವರದಿಯನ್ನು ಉಳಿಸಲು ಸಾಧ್ಯವಾಗಿಲ್ಲ."

#: ../src/savers.py:34
#, python-format
msgid ""
"Your bug could not be filed due to the following error when communicating "
"with bugzilla:\n"
"\n"
"%s"
msgstr ""
"ಬಗ್‌ಝಿಲ್ಲಾದೊಂದಿಗೆ ವ್ಯವಹರಿಸುವಾಗ ಈ ಕೆಳಗಿನ ದೋಷ ಉಂಟಾದ ಕಾರಣ ನಿಮ್ಮ ದೋಷ ವರದಿಯನ್ನು ಸಲ್ಲಿಸಲು "
"ಸಾಧ್ಯವಾಗಿಲ್ಲ:\n"
"\n"
"%s"

#: ../src/savers.py:37
#, python-format
msgid ""
"Your bug could not be filed due to bad information in the bug fields.  This "
"is most likely an error in the bug filing program:\n"
"\n"
"%s"
msgstr ""
"ದೋಷದ ಸ್ಥಳಗಳಲ್ಲಿನ ತಪ್ಪಾದ ಮಾಹಿತಿಯಿಂದಾಗಿ ನಿಮ್ಮ ದೋಷ ವರದಿಯನ್ನು ಸಲ್ಲಿಸಲು ಸಾಧ್ಯವಾಗಿಲ್ಲ. ಇದು ಬಹುಷಃ ದೋಷ ವರದಿ ಸಲ್ಲಿಕೆ ಪ್ರೊಗ್ರಾಮ್‌ನಲ್ಲಿನ ಒಂದು ದೋಷದ ಕಾರಣದಿಂದಾಗಿರಬಹುದು:\n"
"\n"
"%s"

#: ../src/savers.py:41
msgid "Unable To File Bug"
msgstr "ದೋಷ ವರದಿಯನ್ನು ಸಲ್ಲಿಸಲು ಸಾಧ್ಯವಾಗಿಲ್ಲ"

#: ../src/savers.py:47
msgid "Bug Filing Not Supported"
msgstr "ದೋಷ ವರದಿ ಸಲ್ಲಿಕೆಗೆ ಬೆಂಬಲವಿರುವುದಿಲ್ಲ"

#: ../src/savers.py:48
msgid ""
"Your distribution does not provide a supported bug filing system, so you "
"cannot save your exception this way."
msgstr "ನಿಮ್ಮ ವಿತರಣೆಯು ಒಂದು ಬೆಂಬಲಿತವಾದ ದೋಷ ವರದಿ ಸಲ್ಲಿಕೆಯ ವ್ಯವಸ್ಥೆಯನ್ನು ಒದಗಿಸುವುದಿಲ್ಲ, ಆದ್ದರಿಂದ ನೀವು ನಿಮ್ಮ ಆಕ್ಷೇಪಣೆಯನ್ನು ಈ ರೀತಿಯಲ್ಲಿ ಉಳಿಸುವಂತಿಲ್ಲ."

#: ../src/savers.py:54
msgid "Invalid Bug Information"
msgstr "ಅಮಾನ್ಯವಾದ ದೋಷ ಮಾಹಿತಿ"

#: ../src/savers.py:55
msgid "Please provide a valid username, password, and short bug description."
msgstr "ಒಂದು ಮಾನ್ಯವಾದ ಬಳಕೆದಾರ ಹೆಸರು, ಗುಪ್ತಪದ, ಹಾಗು ದೋಷದ ಸಂಕ್ಷಿಪ್ತ ವಿವರಣೆಯನ್ನು ಒದಗಿಸಿ."

#: ../src/savers.py:62
msgid "Unable To Login"
msgstr "ಪ್ರವೇಶವನ್ನು ಪಡೆಯಲು ಸಾಧ್ಯವಾಗಿಲ್ಲ"

#: ../src/savers.py:63
#, python-format
msgid "There was an error logging into %s using the provided username and password."
msgstr "ಒದಗಿಸಲಾದ ಬಳಕೆದಾರ ಹೆಸರು ಹಾಗು ಗುಪ್ತಪದವನ್ನು ಬಳಸಿಕೊಂಡು %s ಗೆ ದಾಖಲಾಗುವಲ್ಲಿ ದೋಷ ಎದುರಾಗಿದೆ."

#. Tell the user we created a new bug for them and that they should
#. go add a descriptive comment.
#: ../src/savers.py:99
msgid "Bug Created"
msgstr "ದೋಷ ವರದಿಯನ್ನು ರಚಿಸಲಾಗಿದೆ"

#: ../src/savers.py:100
#, python-format
msgid ""
"A new bug has been created with your traceback attached. Please add "
"additional information such as what you were doing when you encountered the "
"bug, screenshots, and whatever else is appropriate to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"ನಿಮ್ಮ ಟ್ರೇಸ್‌ಬ್ಯಾಕ್‌ ಅನ್ನು ಲಗತ್ತಿಸಲಾದ ಒಂದು ಹೊಸ ದೋಷ ವರದಿಯನ್ನು ಸಲ್ಲಿಸಲಾಗಿದೆ.  ದಯವಿಟ್ಟು ಈ ದೋಷವು ಸಂಭವಿಸಿದಾಗ ನೀವು ಏನು ಮಾಡುತ್ತಿದ್ದೀರಿ, ಅದರ ತೆರೆಚಿತ್ರಗಳು, ಹಾಗು ಈ ದೋಷ ವರದಿಗೆ ಸೂಕ್ತವಾದ ಬೇರಾವುದೆ ಮಾಹಿತಿಗಳಿದ್ದಲ್ಲಿ ಅವುಗಳನ್ನು ಸೇರಿಸಿ:\n"
"\n"
"%s/%s"

#. Tell the user which bug they've been CC'd on and that they should
#. go add a descriptive comment.
#: ../src/savers.py:114
msgid "Bug Updated"
msgstr "ದೋಷ ವರದಿಯನ್ನು ಅಪ್‍ಡೇಟ್ ಮಾಡಲಾಗಿದೆ"

#: ../src/savers.py:115
#, python-format
msgid ""
"A bug with your information already exists.  Your account has been added to "
"the CC list and your traceback added as a comment.  Please add additional "
"descriptive information to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"ನೀವು ಒದಗಿಸಿದ ಮಾಹಿತಿಯನ್ನು ಒಳಗೊಂಡ ಒಂದು ದೋಷ ವರದಿಯು ಈಗಾಗಲೆ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ.  ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಅದರ CC ಪಟ್ಟಿಗೆ ಸೇರ್ಪಡಿಸಲಾಗಿದೆ ಹಾಗು ನಿಮ್ಮ ಟ್ರೇಸ್‌ಬ್ಯಾಕ್ ಅನ್ನು ಒಂದು ಅಭಿಪ್ರಾಯವಾಗಿ ಸೇರಿಸಲಾಗಿದೆ. ದಯವಿಟ್ಟು ಈ ಕೆಳಗಿನ ದೋಷಕ್ಕಾಗಿ ವಿವರವಾದ ಮಾಹಿತಿಗಳನ್ನು ಸೇರಿಸಿ:\n"
"\n"
"%s/%s"

#. Set the buttons.
#: ../src/ui/gui.py:85
msgid "_Debug"
msgstr "ದೋಷನಿವಾರಣೆ (_D)"

#: ../src/ui/gui.py:87 ../src/ui/gui.py:152
msgid "_Exit"
msgstr "ನಿರ್ಗಮಿಸು (_E)"

#: ../src/ui/gui.py:92
msgid ""
"An unhandled exception has occurred.  This is most likely a bug.  Please "
"save a copy of the detailed exception and file a bug report."
msgstr ""
"ಒಂದು ನಿಭಾಯಿಸದ ತೊಡಕು ಕಂಡುಬಂದಿದೆ.  ಇದು ಬಹುಶಃ ದೋಷವಿದ್ದಿರಬೇಕು. ದಯವಿಟ್ಟು ಈ ತೊಡಕುಗಳ "
"ವಿವರಗಳ ಪ್ರತಿಯನ್ನು ಉಳಿಸಿಕೊಂಡು ಈ ತಂತ್ರಾಂಶವನ್ನು ಒದಗಿಸಿದವರಲ್ಲಿ."

#: tmp/detailed-dialog.glade.h:1
msgid "Info"
msgstr "ಮಾಹಿತಿ"

#: tmp/detailed-dialog.glade.h:2
msgid "_Details"
msgstr "ವಿವರಗಳು(_D)"

#: tmp/exnSave.glade.h:1
msgid "Bug _description"
msgstr "ದೋಷ ವಿವರಣೆ(_d)"

#: tmp/exnSave.glade.h:2
msgid "Destination _file"
msgstr "ಗುರಿ ಕಡತ(_f)"

#: tmp/exnSave.glade.h:3
msgid ""
"Local storage\n"
"Bugzilla\n"
"Remote server (scp)"
msgstr ""
"ಸ್ಥಳೀಯ ಶೇಖರಣೆ\n"
"ಬಗ್‌ಝಿಲ್ಲಾ\n"
"ದೂರಸ್ಥ ಪರಿಚಾರಕ (scp)"

#: tmp/exnSave.glade.h:6
msgid "Please choose a destination for saving your traceback."
msgstr "ನಿಮ್ಮ ಟ್ರೇಸ್‌ಬ್ಯಾಕ್‌ ಅನ್ನು ಉಳಿಸಲು ಒಂದು ಗುರಿಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ."

#: tmp/exnSave.glade.h:7
msgid "Save"
msgstr "ಉಳಿಸು"

#: tmp/exnSave.glade.h:8
msgid "Select A File"
msgstr "ಒಂದು ಕಡತವನ್ನು ಆರಿಸಿ"

#: tmp/exnSave.glade.h:9
msgid "_Host (host:port)"
msgstr "ಅತಿಥೇಯ (host:port)(_H)"

#: tmp/exnSave.glade.h:10
msgid "_Password"
msgstr "ಗುಪ್ತಪದ(_P)"

#: tmp/exnSave.glade.h:11
msgid "_User name"
msgstr "ಬಳಕೆದಾರ ಹೆಸರು(_U)"

