msgid ""
msgstr ""
"Project-Id-Version: python-meh\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-07-16 15:00-0400\n"
"PO-Revision-Date: \n"
"Last-Translator: Rui Gouveia <rui.gouveia@globaltek.pt>\n"
"Language-Team: pt <fedora-trans-pt@redhat.com>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Poedit-Language: Portuguese\n"
"X-Poedit-Country: PORTUGAL\n"

#: ../src/handler.py:209
msgid "Dump Written"
msgstr "Resultado Escrito"

#: ../src/handler.py:210
msgid "The error file has been successfully written to the disk.  The program will now exit."
msgstr "O erro foi gravado em disco com sucesso.  O programa vai agora terminar."

#: ../src/handler.py:215
msgid "Dump Not Written"
msgstr "Resultado Não Escrito"

#: ../src/handler.py:216
msgid "There was a problem writing the error report."
msgstr "Houve um problema ao gravar o relatório."

#: ../src/handler.py:219
msgid "No Network Available"
msgstr "Sem Rede Disponível"

#: ../src/handler.py:220
msgid "Cannot save a bug report since there is no active network device available."
msgstr "Não é possível gravar um relatório de erros por não haver nenhum dispositivo de rede activo disponível."

#: ../src/savers.py:34
#, python-format
msgid ""
"Your bug could not be filed due to the following error when communicating with bugzilla:\n"
"\n"
"%s"
msgstr ""
"O seu erro não pôde ser relatado devido ao seguinte erro durante a comunicação com o Bugzilla:\n"
"\n"
"%s"

#: ../src/savers.py:37
#, python-format
msgid ""
"Your bug could not be filed due to bad information in the bug fields.  This is most likely an error in the bug filing program:\n"
"\n"
"%s"
msgstr ""
"O erro não pode ser submetido devido a má informação nos campos do erro.  Isto é provavelmente um erro na aplicação de submissão de erros:\n"
"\n"
"%s"

#: ../src/savers.py:41
msgid "Unable To File Bug"
msgstr "Não é Possível Enviar o Erro"

#: ../src/savers.py:47
msgid "Bug Filing Not Supported"
msgstr "O Envio do Erro Não é Suportado"

#: ../src/savers.py:48
msgid "Your distribution does not provide a supported bug filing system, so you cannot save your exception this way."
msgstr "A sua distribuição não oferece um sistema de comunicação de erros suportado, pelo que não poderá guardar a sua excepção desta forma."

#: ../src/savers.py:54
msgid "Invalid Bug Information"
msgstr "Informação do Erro Inválida"

#: ../src/savers.py:55
msgid "Please provide a valid username, password, and short bug description."
msgstr "Por favor, indique um utilizador, uma senha válidos, assim como uma breve descrição do erro."

#: ../src/savers.py:62
msgid "Unable To Login"
msgstr "Não é Possível Iniciar Sessão"

#: ../src/savers.py:63
#, python-format
msgid "There was an error logging into %s using the provided username and password."
msgstr "Ocorreu um erro ao iniciar sessão em %s com o utilizador e senha indicados."

#. Tell the user we created a new bug for them and that they should
#. go add a descriptive comment.
#: ../src/savers.py:99
msgid "Bug Created"
msgstr "Erro Criado"

#: ../src/savers.py:100
#, python-format
msgid ""
"A new bug has been created with your traceback attached. Please add additional information such as what you were doing when you encountered the bug, screenshots, and whatever else is appropriate to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"Foi criado um novo erro com o seu registo de chamadas em anexo. Por favor adicione algumas informações adicionais, como o que estava a fazer quando lhe ocorreu o erro, algumas imagens e tudo o que seja apropriado para o seguinte erro:\n"
"\n"
"%s/%s"

#. Tell the user which bug they've been CC'd on and that they should
#. go add a descriptive comment.
#: ../src/savers.py:114
msgid "Bug Updated"
msgstr "Erro Actualizado"

#: ../src/savers.py:115
#, python-format
msgid ""
"A bug with your information already exists.  Your account has been added to the CC list and your traceback added as a comment.  Please add additional descriptive information to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"Já existe um erro com a sua informação. A sua conta foi adicionada à lista de CC e o seu registo de chamadas foi adicionado como um comentário. Por favor, adicione mais informações descritivas do seguinte erro:\n"
"\n"
"%s/%s"

#. Set the buttons.
#: ../src/ui/gui.py:85
msgid "_Debug"
msgstr "_Depurar"

#: ../src/ui/gui.py:87
#: ../src/ui/gui.py:152
msgid "_Exit"
msgstr "_Sair"

#: ../src/ui/gui.py:92
msgid "An unhandled exception has occurred.  This is most likely a bug.  Please save a copy of the detailed exception and file a bug report."
msgstr "Ocorreu um erro não recuperável.  Provavelmente isto é um erro do programa. Por favor, guarde a cópia detalhada da excepção e envie um relatório do erro."

#: tmp/detailed-dialog.glade.h:1
msgid "Info"
msgstr "Info"

#: tmp/detailed-dialog.glade.h:2
msgid "_Details"
msgstr "_Detalhes"

#: tmp/exnSave.glade.h:1
msgid "Bug _description"
msgstr "_Descrição do erro"

#: tmp/exnSave.glade.h:2
msgid "Destination _file"
msgstr "_Ficheiro de destino"

#: tmp/exnSave.glade.h:3
msgid ""
"Local storage\n"
"Bugzilla\n"
"Remote server (scp)"
msgstr ""
"Armazenamento local\n"
"Bugzilla\n"
"Servidor remoto (scp)"

#: tmp/exnSave.glade.h:6
msgid "Please choose a destination for saving your traceback."
msgstr "Por favor, escolha um destino para gravar o registo de traçagem."

#: tmp/exnSave.glade.h:7
msgid "Save"
msgstr "Gravar"

#: tmp/exnSave.glade.h:8
msgid "Select A File"
msgstr "Seleccione Um Ficheiro"

#: tmp/exnSave.glade.h:9
msgid "_Host (host:port)"
msgstr "_Servidor (máquina:porto)"

#: tmp/exnSave.glade.h:10
msgid "_Password"
msgstr "_Senha"

#: tmp/exnSave.glade.h:11
msgid "_User name"
msgstr "_Utilizador"

