# translation of ru.po to Russian
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Anatoliyg Guskov <anatoliy.guskov@gmail.com>, 2009.
# Yulia <ypoyarko@redhat.com>, 2009.
msgid ""
msgstr ""
"Project-Id-Version: ru\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-07-16 15:00-0400\n"
"PO-Revision-Date: 2009-12-08 12:14+1100\n"
"Last-Translator: Yulia <ypoyarko@redhat.com>\n"
"Language-Team: Russian <fedora-trans-ru@redhat.com>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: KBabel 1.11.4\n"

#: ../src/handler.py:209
msgid "Dump Written"
msgstr "Дамп записан"

#: ../src/handler.py:210
msgid ""
"The error file has been successfully written to the disk.  The program will "
"now exit."
msgstr "Файл ошибок успешно записан на диск.  Программа будет завершена."

#: ../src/handler.py:215
msgid "Dump Not Written"
msgstr "Дамп не записан"

#: ../src/handler.py:216
msgid "There was a problem writing the error report."
msgstr "Проблема при записи отчёта об ошибках."

#: ../src/handler.py:219
msgid "No Network Available"
msgstr "Сеть недоступна"

#: ../src/handler.py:220
msgid "Cannot save a bug report since there is no active network device available."
msgstr ""
"Не удалось сохранить отчёт об ошибках, поскольку недоступны активные сетевые "
"устройства."

#: ../src/savers.py:34
#, python-format
msgid ""
"Your bug could not be filed due to the following error when communicating "
"with bugzilla:\n"
"\n"
"%s"
msgstr ""
"Не удалось создать отчёт об ошибке из-за проблемы при подключении к Bugzilla:\n"
"\n"
"%s"

#: ../src/savers.py:37
#, python-format
msgid ""
"Your bug could not be filed due to bad information in the bug fields.  This "
"is most likely an error in the bug filing program:\n"
"\n"
"%s"
msgstr ""
"Не удалось создать отчёт об ошибке, так как поля содержат недопустимые данные. Возможная причина &mdash; ошибка в программе создания отчётов:\n"
"\n"
"%s"

#: ../src/savers.py:41
msgid "Unable To File Bug"
msgstr "Не удалось создать запрос"

#: ../src/savers.py:47
msgid "Bug Filing Not Supported"
msgstr "Создание отчётов об ошибках не поддерживается"

#: ../src/savers.py:48
msgid ""
"Your distribution does not provide a supported bug filing system, so you "
"cannot save your exception this way."
msgstr "Ваш дистрибутив не поддерживает создание отчётов об ошибках, поэтому вы не можете сохранить ваше исключение таким способом."

#: ../src/savers.py:54
msgid "Invalid Bug Information"
msgstr "Неверная информация об ошибке"

#: ../src/savers.py:55
msgid "Please provide a valid username, password, and short bug description."
msgstr ""
"Введите действительное имя пользователя, пароль и краткое "
"описание ошибки."

#: ../src/savers.py:62
msgid "Unable To Login"
msgstr "Не удаётся войти"

#: ../src/savers.py:63
#, python-format
msgid "There was an error logging into %s using the provided username and password."
msgstr ""
"Произошла ошибка входа в %s используя предоставленные имя пользователя и "
"пароль."

#. Tell the user we created a new bug for them and that they should
#. go add a descriptive comment.
#: ../src/savers.py:99
msgid "Bug Created"
msgstr "Отчёт об ошибке создан"

#: ../src/savers.py:100
#, python-format
msgid ""
"A new bug has been created with your traceback attached. Please add "
"additional information such as what you were doing when you encountered the "
"bug, screenshots, and whatever else is appropriate to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"Создан новый отчёт об ошибке с вложением трассировки. Добавьте дополнительную информацию, например, опишите, как и где вы столкнулись с этой ошибкой и по возможности приложите снимок экрана:\n"
"\n"
"%s/%s"

#. Tell the user which bug they've been CC'd on and that they should
#. go add a descriptive comment.
#: ../src/savers.py:114
msgid "Bug Updated"
msgstr "Отчёт обновлён"

#: ../src/savers.py:115
#, python-format
msgid ""
"A bug with your information already exists.  Your account has been added to "
"the CC list and your traceback added as a comment.  Please add additional "
"descriptive information to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"Запрос с этой информацией уже существует.  Ваша учётная запись была добавлена в список CC и данные трассировки добавлены в качестве комментария.  Пожалуйста, добавьте дополнительную информацию к следующей ошибке:\n"
"\n"
"%s/%s"

#. Set the buttons.
#: ../src/ui/gui.py:85
msgid "_Debug"
msgstr "_Отладка"

#: ../src/ui/gui.py:87 ../src/ui/gui.py:152
msgid "_Exit"
msgstr "В_ыход"

#: ../src/ui/gui.py:92
msgid ""
"An unhandled exception has occurred.  This is most likely a bug.  Please "
"save a copy of the detailed exception and file a bug report."
msgstr "Произошло необрабатываемое исключение. Вероятно, это ошибка. Пожалуйста, сохраните копию исключения и создайте отчёт об ошибке."

#: tmp/detailed-dialog.glade.h:1
msgid "Info"
msgstr "Инфо"

#: tmp/detailed-dialog.glade.h:2
msgid "_Details"
msgstr "_Подробности"

#: tmp/exnSave.glade.h:1
msgid "Bug _description"
msgstr "Описание _ошибки"

#: tmp/exnSave.glade.h:2
msgid "Destination _file"
msgstr "Выходной _файл"

#: tmp/exnSave.glade.h:3
msgid ""
"Local storage\n"
"Bugzilla\n"
"Remote server (scp)"
msgstr ""
"Локальное хранилище\n"
"Bugzilla\n"
"Удалённый сервер (scp)"

#: tmp/exnSave.glade.h:6
msgid "Please choose a destination for saving your traceback."
msgstr "Укажите место для сохранения информации трассировки."

#: tmp/exnSave.glade.h:7
msgid "Save"
msgstr "Сохранить"

#: tmp/exnSave.glade.h:8
msgid "Select A File"
msgstr "Выберите файл"

#: tmp/exnSave.glade.h:9
msgid "_Host (host:port)"
msgstr "_Узел (узел:порт)"

#: tmp/exnSave.glade.h:10
msgid "_Password"
msgstr "_Пароль"

#: tmp/exnSave.glade.h:11
msgid "_User name"
msgstr "_Имя пользователя"

